/*

	DQL - Data Query Language

*/
USE Optus;


SELECT * FROM Usuario;
SELECT * FROM Estilo;
SELECT * FROM Artista;
SELECT * FROM Album;
SELECT * FROM EstiloAlbum;


--SELECIONEI UM ALBUM A PARTIR DO SEU ID
SELECT * FROM Album WHERE IdAlbum = 2;

--SELECIONEI UM ESTILO A PARTIR DE 2 LETRAS INICIAS
SELECT * FROM Estilo WHERE Nome LIKE '%Ro%';

--SELECIONEI OS ARTISTAS POR ORDEM 
SELECT * FROM Artista ORDER BY Nome;
