USE Veterianario;
/*

	DQL - Data Query Language

*/

SELECT * FROM TipoDePet;
SELECT * FROM Dono;
SELECT * FROM Clinica;
SELECT * FROM Raca;
SELECT * FROM ProfissionalVeterinario;
SELECT * FROM Pet;
SELECT * FROM Atendimento;

--SELECIONAMOS UMA CLINICA ESPECIFICA ATRAVES DO SEU ID
SELECT * FROM Clinica WHERE IdClinica = 2;

--SELECIONAMOS POR ORDEM 
SELECT * FROM Pet ORDER BY IdPet;

--VERIFICAMOS O AGENDAMENTOS QUE AINDA NÃO FORAM REALIZADOS NA SEMANA
SELECT * FROM Atendimento WHERE
	DataDeAtendimento BETWEEN '2020-03-06T12:00:00' AND '2020-08-17T10:00:00' 